### ISSUE TITLE
Unexpected "could not find implicit value" and need for `sealed` when using `discriminator` and `key`

### ISSUE THREAD

**Issue by arkban** [rallyhealth/weePickle#64]
I ran into an unexpected "could not find implicit value" errors and need to use `sealed` when making hierarchy's of `discriminator` and `key`. Here's an example:

# Could not find implicit value for parameter e

```scala
import com.rallyhealth.weepickle.v1.WeePickle
import com.rallyhealth.weepickle.v1.implicits.{discriminator, key}

@discriminator("kind")
sealed trait A {

  def a: String
}

object A {

  @key("A1")
  case class A1(override val a: String) extends A

  object A1 {

    implicit val format: WeePickle.FromTo[A1] = WeePickle.macroFromTo[A1]
  }

  trait B extends A {

    def b: String
  }

  object B {

    @key("B1")
    case class B1(override val a: String, override val b: String) extends B

    object B1 {

      implicit val format: WeePickle.FromTo[B1] = WeePickle.macroFromTo[B1]
    }
  }
}

case class Container(a: A)

object Container {

  implicit val format: WeePickle.FromTo[Container] = WeePickle.macroFromTo[Container]
}
```

The error you get is:
```
/../Temp.scala:41:75
could not find implicit value for parameter e: com.rallyhealth.weepickle.v1.WeePickle.To[A]
  implicit val format: WeePickle.FromTo[Container] = WeePickle.macroFromTo[Container]

```
You can resolve that by defining a format for `A` -- which requires you to do the same for `B`.

# Sealed

Once you fix that you get a new error:

```
/.../Temp.scala:35:69
[error] The referenced trait [[B]] must be sealed.
    implicit val format: WeePickle.FromTo[B] = WeePickle.macroFromTo[B]
```

Which you can solve by adding `sealed` to `B`. 

# Inconsistent tag names

Now it compiles! But you get a runtime error if you try to parse something:
```
java.lang.IllegalArgumentException: Inconsistent tag names: [kind, $type]
```

You can fix that by replicating the `@discriminator("kind")` to `B`

# Conclusion

After that it all works! 

Yet it seems like it should work without these extra changes...

**Comment by htmldoug** [comment]
These errors make sense to me.

Type hierarchies with multiple sealed traits is a bit of an edge case. The macros inherited from upickle have been a bit too opinionated for some cases, but it's always possible to omit the macro and define a custom `FromTo`.

Haoyi has written that full auto derivation is quite slow, which is why (u|wee)Pickle rely on semi-auto derivation. I'm not sure how true that still is today, but it'd likely require a rewrite of all the macros. Volunteers welcome, I suppose.

Thanks for raising this to see what could be done, but I can't think of any actionable low-hanging fruit. Feel free to reopen if you think of anything.
